using LonecraftGames.Toolkit.Core.Utilis;
using UnityEngine;

namespace LonecraftGames.Toolkit.Core.Events
{
    [CreateAssetMenu(fileName = "GameStateEvent", menuName = "LonecraftGames/Events/GameStateEvent", order = 1)]
    public class GameStateEvent : EventChannel<Enums.GameState>
    {
        // This class is generated by EventChannelEditor.
    }
}
