using LonecraftGames.Toolkit.Core.Events;
using UnityEngine;

namespace LonecraftGames.Toolkit.Gameplay.HealthPro
{
    /// <summary>
    ///  Event channel for health changed events.
    /// </summary>
    [CreateAssetMenu(fileName = "OnHealthChangedEventChannel", menuName = "LonecraftGames/Events/HealthPro/OnHealthChangedEventChannel")]
    public class OnHealthChangedEventChannel : EventChannel<HealthEventArgs>
    {
        // This class is generated by EventChannelEditor.
    }
}
